/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;


public class App {

    public static void main(String[] args) {
        //We had to set this to zero... because it made us
        Quote[] quotes = null;
        String url = "http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote";
        String singleQuote = "";
        try {
            singleQuote = readFromUrl(url).toString();
        } catch (IOException e) {
            try {
                quotes = readFromJson("src/main/resources/recentquotes.json");
            } catch (IOException err) {
                e.printStackTrace();
            }
        }
        //Get random int for quote
        if (singleQuote != null){
            System.out.println(singleQuote);
        } else {
            System.out.println(quotes[(int)(Math.random() * quotes.length )].toString());
        }
    }

    // This file reads from the json and returns an array of quotes
    public static Quote[] readFromJson(String filename) throws IOException {
        Gson read = new Gson();
        InputStream inStream = new FileInputStream(filename);
        BufferedReader buffer = new BufferedReader(new InputStreamReader(inStream));
        Quote[] quote = read.fromJson(buffer, Quote[].class);
        return quote;
    }

    public static Quote readFromUrl(String url) throws IOException {
        Gson gson = new Gson();
        URL quoteUrl = new URL(url);
        HttpURLConnection con = (HttpURLConnection) quoteUrl.openConnection();
        BufferedReader input = new BufferedReader( new InputStreamReader( con.getInputStream()));
        Quote quote = gson.fromJson(input, Quote.class);
        return quote;
    }

    public static void addToQuoteFile(String filepath){

    }
}

//.getAsJsonArray();